version: "3"

services:
  symfony:
    container_name: eshop_symfony
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html

  mysql:
    container_name: eshop_mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: eshop
      MYSQL_USER: eshop
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/.data/db:/var/lib/mysql

  phpmyadmin:
    container_name: eshop_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    restart: always